apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  root-password: "DaolTS1!"  # 변경 필수!
  username: "devuser"  # 실제 사용자명으로 변경
  password: "DaolTS1!"  # 변경 필수!
  
# 주의: 실제 운영에서는 Sealed Secrets 또는 External Secrets 사용